In [100]:
import zipfile
from google.colab import drive
drive.mount('/content/drive/')

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

In [0]:
import os
os.getcwd()
os.chdir('/content/drive/My Drive/hdfc/')

In [102]:
import pandas as pd
import numpy as np
df_train=pd.read_csv("DataSet/Train.csv")
df_test=pd.read_csv("DataSet/Test.csv")

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (746,835) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (700,731,740,752,761,789,811,820,829,841,850) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [112]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20442 entries, 0 to 20441
Columns: 2176 entries, Col1 to Col2397
dtypes: float64(630), int64(1545), object(1)
memory usage: 339.4+ MB

In [113]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17521 entries, 0 to 17520
Columns: 2177 entries, Col1 to Col2397
dtypes: float64(628), int64(1548), object(1)
memory usage: 291.0+ MB

In [0]:
#remove those columns that have only Nan values
def remove_nan(df):
  for i in range(3,2395):
      try:
          p=all(df['Col{}'.format(i)].isnull())
          if p :
              df=df.drop(['Col{}'.format(i)],axis=1)
      except KeyError:
          pass
  return df

In [0]:
def cleaning_rows(df):
    list1=[]
    for i in range(3,2398):
        try:
          #calculate sum of nan values of every columns and go ahead
            sum_Nan=df['Col{}'.format(i)].isnull().sum()
            #70% data nan then remove columns
            #
            x70=(17521*7)/10
            x50=(17521*5)/10
            #if Nan value found then if condition true
            if sum_Nan >=x70:
                #print(i)
                list1.append(i)
                df=df.drop(['Col{}'.format(i)],axis=1)
              #if columns have morethan 50% data nan value and less 70% then  direct fill with 0 
            elif  sum_Nan <x70 and sum_Nan>x50:
                df['Col{}'.format(i)]=df['Col{}'.format(i)].fillna(np.mean(0))

            elif sum_Nan<x50:
                #then fill mean values
                df['Col{}'.format(i)]=df['Col{}'.format(i)].fillna(np.mean(df['Col{}'.format(i)]))


        except KeyError:
            pass
    return df,list1

In [0]:
df_train=remove_nan(df_train)
df_train,list1=cleaning_rows(df_train)

In [0]:
df_test=remove_nan(df_test)
df_test,list2=cleaning_rows(df_test)

In [0]:
#extract those columns that removed in test file and not yet removed from train files
extra_columns=[x for x in list2 if x not in list1]

In [0]:
def remove_extra_columns(df,extra_columns):
  for i in extra_columns:
    df=df.drop(['Col{}'.format(i)],axis=1)
  return df

In [0]:
df_train=remove_extra_columns(df_train,extra_columns)