In [0]:
#this code 
import zipfile
from google.colab import drive
drive.mount('/content/drive/')

In [0]:
#zip_ref = zipfile.ZipFile("/content/drive/My Drive/hdfc/data.zip", 'r')
#zip_ref.extractall("/content/drive/My Drive/hdfc/")
#zip_ref.close()

In [0]:
import os
os.getcwd()
os.chdir('/content/drive/My Drive/hdfc/')

In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [0]:
df=pd.read_csv("DataSet/Train.csv")

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17521 entries, 0 to 17520
Columns: 2202 entries, Col1 to Col2397
dtypes: float64(653), int64(1548), object(1)
memory usage: 294.4+ MB

In [0]:
#remove those columns that have only Nan values
for i in range(3,2395):
    try:
        p=all(df['Col{}'.format(i)].isnull())
        if p :
            df=df.drop(['Col{}'.format(i)],axis=1)
    except KeyError:
        pass

In [0]:
#preprocessing 
#1.check dataset contains any null
#2.check categorical data
#3.need decimal scalling

df.isnull().any(axis=0)

In [0]:
for i in range(3,999):
    try:
        sum_Nan=df['Col{}'.format(i)].isnull().sum()
        #70% data nan then remove columns
        #
        x70=(17521*7)/10
        x50=(17521*5)/10
        #if Nan value found then if condition true
        if sum_Nan >=x70:
            df=df.drop(['Col{}'.format(i)],axis=1)
           #if columns have morethan 50% data nan value and less 70% then  direct fill with 0 
        elif  sum_Nan <x70 and sum_Nan>x50:
            df['Col{}'.format(i)]=df['Col{}'.format(i)].fillna(np.mean(0))

        elif sum_Nan<x50:
            #then fill mean values
            df['Col{}'.format(i)]=df['Col{}'.format(i)].fillna(np.mean(df['Col{}'.format(i)]))


    except KeyError:
        pass